# Generated by Django 4.2.16 on 2024-12-06 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nettikirppis', '0002_comment_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nettikirppis.comment')),
                ('original_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel', to='nettikirppis.comment')),
            ],
            bases=('nettikirppis.comment',),
        ),
    ]
