# Generated by Django 4.2.16 on 2024-12-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettikirppis', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='visible',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
