# Generated by Django 4.2.16 on 2024-12-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettikirppis', '0003_comment_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
